apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lion
  template:
    metadata:
      labels:
        app: lion
    spec:
      containers:
      - image: okteto.dev/lion:latest
        name: lion
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animeflick.net"
        - name: Vless_UUID
          value: "72b4f5c0-90e8-4674-af6f-c7f85a810670"
        - name: Vless_Path
          value: "/root-etc-apt"
        - name: Vmess_UUID
          value: "72b4f5c0-90e8-4674-af6f-c7f85a810670"
        - name: Vmess_Path
          value: "/home-avi-video"
        - name: Share_Path
          value: "/share233"
