apiVersion: apps/v1
kind: Deployment
metadata:
  name: mouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mouse
  template:
    metadata:
      labels:
        app: mouse
    spec:
      containers:
      - image: okteto.dev/mouse:latest
        name: mouse
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animeflick.net"
        - name: Vless_UUID
          value: "14c26de5-c99d-4189-83f9-2db35963ed6f"
        - name: Vless_Path
          value: "/root-etc-apt"
        - name: Vmess_UUID
          value: "14c26de5-c99d-4189-83f9-2db35963ed6f"
        - name: Vmess_Path
          value: "/home-avi-video"
        - name: Share_Path
          value: "/share233"
